[package]
name = "rekapundi"
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https:/github.com/Tango992/rekapundi"
authors = [
    "Daniel Osvaldo Rahmanto <daniel.rahmanto@gmail.com>",
]

[dependencies]
anyhow = "1.0.97"
axum = "0.8.3"
sqlx = { version = "0.8", features = [ "json", "postgres", "runtime-tokio" ] }
tokio = { version = "1.44.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["compression-full", "trace"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
serial_test = "*"
